channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=23.3.1
- pip:
  - mlflow==2.12.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pyyaml==6.0.1
  - scikit-learn==1.4.0
  - scipy==1.12.0
name: mlflow-env
